name: CustomInteractions
main: net.projectzombie.custominteractions.main.Main
depend: [WorldEdit,WorldGuard,BlockBuffer]
version: 1.0
commands:
  bp:
    description: Nope.
    usage: "WIP"
  treesnow:
    description: Nope.
    usage: "WIP"
